"use client";

import React from "react";
import { Badge } from "@/components/ui/badge";
import { Cpu, Layout, Users, Zap, Shield, Globe } from "lucide-react";

export default function ServicesPage() {
  const services = [
    {
      title: "Interactive Bootcamps",
      desc: "Intensive training programs designed to take you from zero to job-ready in months.",
      icon: Zap,
    },
    {
      title: "AI Learning Paths",
      desc: "Customized curricula generated by our AI based on your specific goals and pace.",
      icon: Cpu,
    },
    {
      title: "Enterprise Training",
      desc: "Scalable learning solutions for teams looking to upskill in modern technologies.",
      icon: Layout,
    },
    {
      title: "1-on-1 Mentorship",
      desc: "Connect with industry experts for personalized guidance and code reviews.",
      icon: Users,
    },
    {
      title: "Verified Certs",
      desc: "Blockchain-backed certifications that prove your skills to employers globally.",
      icon: Shield,
    },
    {
      title: "Global Job Network",
      desc: "Exclusive access to hiring partners looking for LetsCatchUp graduates.",
      icon: Globe,
    },
  ];

  return (
    <div className="min-h-screen pt-32 pb-20 px-6">
      <div className="max-w-7xl mx-auto space-y-16">
        <div className="text-center space-y-6 max-w-3xl mx-auto">
          <Badge className="glass text-accent border-white/10">Our Solutions</Badge>
          <h1 className="text-5xl font-headline font-bold">Comprehensive <span className="text-gradient">Services</span></h1>
          <p className="text-xl text-gray-400">Everything you need to master the skills of tomorrow, all in one platform.</p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {services.map((service, i) => (
            <div key={i} className="glass-card p-8 group cursor-default floating" style={{ animationDelay: `${i * 0.2}s` }}>
              <div className="w-14 h-14 rounded-2xl bg-white/5 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                <service.icon className="w-7 h-7 text-accent glow-icon" />
              </div>
              <h3 className="text-2xl font-bold mb-4 group-hover:text-accent transition-colors">{service.title}</h3>
              <p className="text-gray-400 leading-relaxed">{service.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
